// GENERATED BY GenerateIconsMapPlugin
// DO NOT EDIT IT MANUALLY
  
export const svgIconsMap = {
  Blocked: () => import('./svg/blocked.svg'),
  Calendar: () => import('./svg/calendar.svg'),
  Feather: () => import('./svg/feather.svg'),
  Flame: () => import('./svg/flame.svg'),
  Game: () => import('./svg/game.svg'),
  Hamburger: () => import('./svg/hamburger.svg'),
} as const;
