import React from 'react';
import s from './buttons.module.scss';
import { Button } from '../../elements/form/button';
import { __ } from '@repo/helpers';


const ButtonsPage: React.FC = () => {
  return (
    <div className={s.buttons}>
      <h1 className="heading heading--h1">
        {__('Buttons_._Heading_._Buttons with autogenerated SVG background')}
      </h1>
      <div className={s.blocks}>
        <div className={s.block}>
          <div className={s.blockTitle}>
            {__('Buttons_._Button_._Filled button without width')}
          </div>
          <Button
            text={__('Buttons_._Button_._Filled button without width')}
            modifiers={['default', 'main']}
          />
        </div>
        <div className={s.block}>
          <div className={s.blockTitle}>
            {__('Buttons_._Button_._Outline button without width')}
          </div>
          <Button
            text={__('Buttons_._Button_._Outline button without width')}
            modifiers={['outline', 'secondary']}
          />
        </div>
      </div>

    </div>
  );
};

export default ButtonsPage;