import React from 'react';
import s from './svgs.module.scss';
import { Button } from '../../elements/form/button';
import { __ } from '@repo/helpers';
import PromotionsSection from './promotions.section';


const SvgsPage: React.FC = () => {
  return (
    <div className={s.svgs}>
      <h1 className="heading heading--h1">
        {__('Svgs_._Heading_._Autogenerated SVG background')}
      </h1>
      <p className={s.pageDescription}>
        {__('Svgs_._Description_._Background is automatically redrawn on any button resize')}
      </p>
      <h2 className="heading heading--h2">
        {__('Svgs_._Heading_._Buttons')}
      </h2>
      <div className={s.blocks}>
        <div className={s.block}>
          <div className={s.blockTitle}>
            {__('Svgs_._Button_._Filled button without width')}
          </div>
          <Button
            text={__('Svgs_._Button_._Filled button without width')}
            modifiers={['default', 'main']}
          />
        </div>
        <div className={s.block}>
          <div className={s.blockTitle}>
            {__('Svgs_._Button_._Outline button without width')}
          </div>
          <Button
            text={__('Svgs_._Button_._Outline button without width')}
            modifiers={['outline', 'secondary']}
          />
        </div>
      </div>
      <h2 className="heading heading--h2">
        {__('Svgs_._Heading_._Promotion card')}
      </h2>
      <div className={s.promo}>
        <PromotionsSection />
      </div>
    </div>
  );
};

export default SvgsPage;